## Lists

In [1]:
mylist = [] # This is an empty list. Lists are the most basic mutable type, and 
            #   are what you should use anytime you will need to add or remove things.
            #   They can hold any combination of any type of object, including
            #   other lists.
mylist.append('to wong foo') # this appends a string
mylist.append([3,5,7]) # this appends a list of numbers
print(mylist)

['to wong foo', [3, 5, 7]]


In [2]:
# Because lists are mutable, you can assign to them and there are methods which 
#   alter them in-place.
mylist[1] = 'is a great movie'
mylist.reverse()
# Addition concatenates lists
print(mylist+[0,0,0,0,0])

['is a great movie', 'to wong foo', 0, 0, 0, 0, 0]


## Tuples

In [3]:
mytup = (1,(2,3),'wow') # Tuples are immutable container types. They are just
                        #   like lists, but they can't be changed once created.
                        #   So: no appending or assignment!

print(mytup)
print(mytup[2][1])
# These are useful if you want to be sure the contents don't change.

(1, (2, 3), 'wow')
o


## Strings

In [4]:
spam = 'Have some spam.' # This is a string. It's an immutable type.
eggs = "Have some eggs." # You can use double or single quotes for strings
                         
print(spam) # Prints the string to the terminal and starts a new line.

Have some spam.


In [5]:
# Remember that Python is base 0.
# Like lists and tuples, strings are "iterables". You can index into them.
# All intervals in Python include the left endpoint and exclude the right one.
# Also: addition concatenates strings
print(spam[0:5] + spam[:10])

Have Have some 


In [6]:
# You can use indexing to go through iterables in different ways
print(eggs[1:10:2])
print(eggs[::-1])

aesm 
.sgge emos evaH


In [7]:
# You can use the format property of a string to replace {} with text, etc.
pirate_call = 'The pirate says {}, {}!!!'.format(2+5,'win')
print(pirate_call)

The pirate says 7, win!!!


## Dictionaries

In [8]:
mydict = {} # This is an empty dict. It's mutable.
            #   Dicts are made up of key-value pairs. Keys can be any immutable,
            #   and they point to a value which can be any object.
            #   While they are iterable (you can iterate through them using 
            #   techniques TBD later), they are NOT ordered in any way.
mydict['color'] = 'blue' # color points to 'blue'
mydict['number'] = 3 # 'number' points to 3
print(mydict)
print(mydict['color'])

{'color': 'blue', 'number': 3}
blue


## Numpy Arrays

In [9]:
import numpy as np
# (Nearly) everything in NumPy uses the array datatype.
# It is mutable, but has a fixed shape and should only contain a single datatype
#   (usually numbers, and most usually floating point numbers)
# You can create an array out of a list, or a list of lists.
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3x3 array of integers
print('A = ')
print(A)
x,y = A.shape
print('The shape of A is {} by {}.'.format(x,y))
B = np.random.rand(3,3) # 3x3 array of floating point numbers between 0 and 1
print('B = ')
print(B)
# All operations are elementwise...
print('Element-wise multiplication:')
print(A*B)
# In Python 3.5+, we also have @ which is matrix multiplication
print('Matrix multiplicaton:')
print(A@B)
# Tons of other routines can be found in the numpy library
# You can get a particular element from a multidimensional array like this:
print('Lucky number {}!'.format(A[2,0])) # row 2, column 0
# Slices (with :) work too, and there are lots of other fancy tricks!

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The shape of A is 3 by 3.
B = 
[[0.44157801 0.44221017 0.46174881]
 [0.87936334 0.30425937 0.49106676]
 [0.56625932 0.14225039 0.09754377]]
Element-wise multiplication:
[[0.44157801 0.88442034 1.38524642]
 [3.51745336 1.52129684 2.94640056]
 [3.96381525 1.13800314 0.87789392]]
Matrix multiplicaton:
[[ 3.89908266  1.47748009  1.73651363]
 [ 9.56068468  4.14363988  4.88759163]
 [15.2222867   6.80979968  8.03866963]]
Lucky number 7!
